// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Token     string           `json:"token"`
	CreatedOn pgtype.Timestamp `json:"created_on"`
	ExpiresOn pgtype.Timestamp `json:"expires_on"`
}

type User struct {
	ID             int32            `json:"id"`
	Username       string           `json:"username"`
	HashedPassword string           `json:"hashed_password"`
	CreatedOn      pgtype.Timestamp `json:"created_on"`
	LastLogin      pgtype.Timestamp `json:"last_login"`
}
