// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Token     string       `json:"token"`
	CreatedOn sql.NullTime `json:"created_on"`
	ExpiresOn time.Time    `json:"expires_on"`
}

type User struct {
	ID             int32        `json:"id"`
	Username       string       `json:"username"`
	HashedPassword string       `json:"hashed_password"`
	CreatedOn      sql.NullTime `json:"created_on"`
	LastLogin      sql.NullTime `json:"last_login"`
}
