// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	Session(ctx context.Context, id int32) (SessionRow, error)
	SessionAdd(ctx context.Context, arg SessionAddParams) error
	UserAdd(ctx context.Context, arg UserAddParams) error
	UserByID(ctx context.Context, id int32) (User, error)
	UserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
