// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dal

import (
	"database/sql"
)

type Foo struct {
	ID   int32          `json:"id"`
	Name sql.NullString `json:"name"`
}
