// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dal

import (
	"context"
)

type Querier interface {
	Foos(ctx context.Context) ([]Foo, error)
}

var _ Querier = (*Queries)(nil)
