// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package dal

import (
	"context"
)

const foos = `-- name: Foos :many
SELECT id, name FROM foo
`

func (q *Queries) Foos(ctx context.Context) ([]Foo, error) {
	rows, err := q.query(ctx, q.foosStmt, foos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
